site_name: kplot Documentation
repo_url: https://github.com/kyashaa/kplot
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            setup_commands:
              - import sys
              - sys.path.insert(0, "src") # ここでsrcをパスに追加
            docstring_style: google
            show_source: true
  - mike
nav:
  - Home: index.md
  - API Reference:
      - kplot: api/kplot.md
