name: Deploy MkDocs with mike

on:
  push:
    branches: [main, develop.v1]
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # mikeが必要とするので全履歴取得

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material "mkdocstrings[python]" mike

      - name: Deploy docs
        run: |
          if [ "${GITHUB_REF_NAME}" = "develop" ]; then
            mike deploy --push --update-aliases dev
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            VERSION="v$(date +'%Y.%m.%d')"   # 例: v2025.09.04
            mike deploy --push --update-aliases $VERSION latest
          fi
